try:
    print(x)
except:
    print("Exception occured and handlled")
